version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWORD=mypassword
      - DB_NAME=ecom
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypassword
volumes:
  db_data: